import { Command } from 'commander';
import { writeFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { loadLatestReport } from '../core/reports.js';
import type { ScanReport, Vulnerability } from '../agents/types.js';

const SEP = chalk.hex('#27272A')('─'.repeat(56));

export const reportCommand = new Command('report')
  .description('Export the latest scan report')
  .option('-d, --dir <path>', 'Project directory', process.cwd())
  .option('--json',           'Export as JSON (default)')
  .option('--md',             'Export as Markdown')
  .option('-o, --output <file>', 'Output file path')
  .action(async (opts) => {
    const cwd: string = opts.dir ?? process.cwd();

    const report = await loadLatestReport(cwd);
    if (!report) {
      console.log();
      console.log(chalk.red('  ✗  No scan report found.'));
      console.log(chalk.hex('#6B7280')('     Run ') + chalk.hex('#7C3AED')('brain scan') + chalk.hex('#6B7280')(' first.\n'));
      process.exit(1);
      return;
    }

    const ext        = opts.md ? 'md' : 'json';
    const outputPath = opts.output ?? join(cwd, '.brainsield', `report-${report.id}.${ext}`);

    if (opts.md) {
      writeFileSync(outputPath, buildMarkdownReport(report), 'utf-8');
    } else {
      writeFileSync(outputPath, JSON.stringify(report, null, 2), 'utf-8');
    }

    console.log();
    console.log(SEP);
    console.log(
      '  ' + chalk.hex('#7C3AED').bold('▐█▌  BrainShield Report') +
      chalk.hex('#3F3F46')('  ·  ') +
      chalk.hex('#6B7280')(ext.toUpperCase())
    );
    console.log(SEP);
    console.log();
    console.log(chalk.green('  ✓  Report exported'));
    console.log(chalk.hex('#6B7280')(`     ${outputPath}`));
    console.log();
    console.log(chalk.hex('#6B7280')(`     Score:    ${report.score}/100`));
    console.log(chalk.hex('#6B7280')(`     Findings: ${report.vulnerabilities.length}`));
    console.log(chalk.hex('#6B7280')(`     Files:    ${report.filesScanned}`));
    console.log(chalk.hex('#6B7280')(`     Date:     ${new Date(report.timestamp).toLocaleString()}`));
    console.log();
  });

// ─── Markdown builder ─────────────────────────────────────────────────────────

function buildMarkdownReport(report: ScanReport): string {
  const { vulnerabilities: vulns, score } = report;
  const countBy = (sev: string) => vulns.filter((v: Vulnerability) => v.severity === sev).length;

  const scoreEmoji = score >= 80 ? '🟢' : score >= 50 ? '🟡' : '🔴';

  const lines: string[] = [
    `# BrainShield Security Report`,
    ``,
    `> Generated by [BrainShield](https://brainsield.dev) — AI-powered security analysis`,
    ``,
    `## Summary`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| Date | ${new Date(report.timestamp).toLocaleString()} |`,
    `| Project | \`${report.cwd}\` |`,
    `| Type | ${report.projectType} |`,
    `| Files Scanned | ${report.filesScanned} |`,
    `| Duration | ${report.duration}ms |`,
    ``,
    `## ${scoreEmoji} Security Score: ${score}/100`,
    ``,
    `\`\`\``,
    `${'█'.repeat(Math.round(score / 5))}${'░'.repeat(20 - Math.round(score / 5))}  ${score}/100  ${score >= 80 ? 'SECURE' : score >= 50 ? 'AT RISK' : 'CRITICAL'}`,
    `\`\`\``,
    ``,
    `| Severity | Count |`,
    `|---|---|`,
    `| 🔴 CRITICAL | ${countBy('CRITICAL')} |`,
    `| 🟠 HIGH     | ${countBy('HIGH')} |`,
    `| 🟡 MEDIUM   | ${countBy('MEDIUM')} |`,
    `| 🔵 LOW      | ${countBy('LOW')} |`,
    ``,
    `## Vulnerabilities`,
    ``,
  ];

  for (const vuln of vulns) {
    const sevEmoji = vuln.severity === 'CRITICAL' ? '🔴'
      : vuln.severity === 'HIGH'   ? '🟠'
      : vuln.severity === 'MEDIUM' ? '🟡'
      : '🔵';

    lines.push(
      `### ${sevEmoji} \`${vuln.id}\` — ${vuln.title}`,
      ``,
      `| Field | Value |`,
      `|---|---|`,
      `| Severity | **${vuln.severity}** |`,
      `| File | \`${vuln.file}${vuln.line ? `:${vuln.line}` : ''}\` |`,
      `| Category | ${vuln.category} |`,
      ...(vuln.cwe   ? [`| CWE | [${vuln.cwe}](https://cwe.mitre.org/data/definitions/${vuln.cwe.replace('CWE-', '')}.html) |`] : []),
      ...(vuln.owasp ? [`| OWASP | ${vuln.owasp} |`] : []),
      ``,
      `**Description:** ${vuln.description}`,
      ``,
      ...(vuln.snippet ? [`**Code:**`, `\`\`\``, vuln.snippet, `\`\`\``, ``] : []),
      ...(vuln.fix ? [`> **Fix:** ${vuln.fix}`, ``] : []),
      `---`,
      ``,
    );
  }

  lines.push(
    `## Agents`,
    ``,
    `| Agent | Findings | Duration |`,
    `|---|---|---|`,
    ...report.agents.map((a) =>
      `| ${a.agentName} | ${a.vulnerabilities.length} | ${a.duration}ms |`
    ),
    ``,
    `---`,
    `*Report generated by [BrainShield](https://brainsield.dev) v${report.id}*`,
  );

  return lines.join('\n');
}
